steps:
  steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json
 
  # Step 2: Set up Terraform
  - name: hashicorp/terraform:1.5.6  # Use an appropriate Terraform version
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        terraform --version
        terraform init

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.5.6
    id: terraform-plan
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        terraform plan -var="project_id=$PROJECT_ID" -out=tfplan

  # Step 4: Terraform Apply
  - name: hashicorp/terraform:1.5.6
    id: terraform-apply
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        terraform apply -auto-approve tfplan

substitutions:
  _PROJECT_ID: "costco-udp"

## Optional: Specify log's bucket
logsBucket: gs://costco-udp-bigquery-logs

# Permissions
timeout: "1200s"  # 20 minutes, adjust as needed
